#!/bin/sh
### BEGIN INIT INFO
# Provides:          kbsearch
# Required-Start:    docker
# Required-Stop:     docker
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: KB Semantic Search stack
### END INIT INFO
DIR=/opt/kbsearch
DC="docker compose -f $DIR/docker-compose.yml"
LOG=$DIR/logs/init.log

case "$1" in
  start)   echo "Starting KBSearch stack..." | tee -a "$LOG"; $DC up -d postgres redis qdrant meili ollama api worker ;;
  stop)    echo "Stopping KBSearch stack..." | tee -a "$LOG"; $DC down ;;
  status)  $DC ps ;;
  restart) $0 stop; $0 start ;;
  *) echo "Usage: /etc/init.d/kbsearch {start|stop|status|restart}"; exit 1 ;;
esac
exit 0

